# Generated by Django 4.1.1 on 2022-10-10 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ingredient", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("comment", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "food_name",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("*", "*"),
                            ("**", "**"),
                            ("***", "***"),
                            ("****", "****"),
                            ("*****", "*****"),
                        ],
                        default="",
                        max_length=40,
                    ),
                ),
                (
                    "cooktime_hour",
                    models.CharField(
                        choices=[
                            ("0", "0"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                        ],
                        default="",
                        max_length=40,
                    ),
                ),
                (
                    "cooktime_minute",
                    models.CharField(
                        choices=[
                            ("10", "10"),
                            ("20", "20"),
                            ("30", "30"),
                            ("40", "40"),
                            ("50", "50"),
                        ],
                        default="",
                        max_length=40,
                    ),
                ),
                (
                    "likes",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "ingredient",
                    models.ManyToManyField(
                        related_name="food_ingredient", to="ingredient.ingredient"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FoodCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "food_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("한식", "한식"),
                            ("양식", "양식"),
                            ("일식", "일식"),
                            ("분식", "분식"),
                            ("베이킹", "베이킹"),
                        ],
                        default="",
                        max_length=40,
                    ),
                ),
                (
                    "machine_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("필요없음", "필요없음"),
                            ("전자레인지", "전자레인지"),
                            ("오븐", "오븐"),
                            ("에어프라이기", "에어프라이기"),
                            ("인덕션", "인덕션"),
                            ("기타", "기타"),
                        ],
                        default="",
                        max_length=40,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipe", models.TextField()),
                (
                    "food",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe",
                        to="food.food",
                    ),
                ),
            ],
        ),
    ]
