# Generated by Django 4.1.1 on 2022-10-10 01:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="like",
            field=models.ManyToManyField(
                related_name="like", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
