# Generated by Django 4.1.1 on 2022-10-10 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="comment_food",
            field=models.ForeignKey(
                default="", on_delete=django.db.models.deletion.CASCADE, to="food.food"
            ),
        ),
    ]
